### ISSUE TITLE
Context

### ISSUE THREAD

**Issue by khufkens** [stineb/mlflx2#4]
Would it be possible to give some context, the formal preprint title and abstract if any?

**Comment by khufkens** [comment]
Fixed https://github.com/geco-bern/mlflx2/commit/e5a4111863d7c28ec4ab6684001023092f224cc1

**Comment by stineb** [comment]
Thanks @khufkens

**Comment by khufkens** [comment]
Please keep an eye on this. The `npp_peng_2023`  (see https://github.com/geco-bern/npp_peng_2023/issues/2) and `mct` repos are equally sloppy in this respect. Perception matters, the main lab page should only contain well curated repos with comprehensive front matter.
